### ISSUE TITLE
Make the localstack image configurable

### ISSUE THREAD

**Issue by jon-rei** [localstack/ci-plugin-circleci#4]
## Describe Request:

Currently I can only use the normal "light" localstack image. But in my CircleCI Pipeline I already know that I want to use the Elasticsearch Service therefore it would be nice if I could directly pull the [localstack/localstack-full](https://hub.docker.com/r/localstack/localstack-full) image so my build time can be reduced.

## Examples:

New parameter e.g.:

```
  image:
    type: string
    default: localstack/localstack
    description: Tag of the localstack/localstack Docker image to use
```

This parameter could be than used to configure a different localstack image:

```
    steps:
      - localstack/startup:
          image: localstack/localstack-full  
```

## Supporting Documentation Links:

https://github.com/localstack/ci-plugin-circleci/blob/main/src/commands/start.yml#L25
https://hub.docker.com/r/localstack/localstack-full
